import fs from "node:fs/promises";
import path from "node:path";
import vm from "node:vm";
import { fileURLToPath } from "node:url";

let runtimeSpecPromise = null;

export class ParseError extends Error {}

function repoRoot() {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
}

function transformJavascriptModule(source) {
  return source
    .replace(/export\s+const\s+([A-Za-z0-9_]+)\s*=/g, "exports.$1 =")
    .replace(/export\s+function\s+([A-Za-z0-9_]+)\s*\(/g, "exports.$1 = function $1(")
    .replace(/export\s+default\s+/g, "exports.default = ");
}

function evaluateJavascriptSegments(segments, filename) {
  const javascript = segments
    .filter((segment) => segment.language === "javascript")
    .map((segment) => segment.source)
    .join("\n\n");
  const exports = {};
  const context = vm.createContext({ exports });
  const script = new vm.Script(transformJavascriptModule(javascript), { filename });
  script.runInContext(context);
  return exports;
}

async function loadJizzModule(relativePath, treeRoot = repoRoot()) {
  const absolutePath = path.join(treeRoot, relativePath);
  const source = await fs.readFile(absolutePath, "utf8");
  const program = parseProgram(source);
  return evaluateJavascriptSegments(program.segments, absolutePath);
}

async function loadRuntimeSpec(treeRoot = repoRoot()) {
  if (runtimeSpecPromise) {
    return runtimeSpecPromise;
  }

  runtimeSpecPromise = Promise.all([
    loadJizzModule("jizzrug/source_model.jizz", treeRoot),
    loadJizzModule("jizzrug/parser.jizz", treeRoot),
    loadJizzModule("jizzrug/manifest.jizz", treeRoot),
    loadJizzModule("jizzrug/transpiler.jizz", treeRoot),
    loadJizzModule("rizz/cli.jizz", treeRoot),
    loadJizzModule("rizz/bootstrap.jizz", treeRoot),
    loadJizzModule("squirt/flush.jizz", treeRoot),
    loadJizzModule("squirt/stream.jizz", treeRoot),
  ]).then(([sourceModel, parser, manifest, transpiler, cli, bootstrap, squirtFlush, squirtStream]) => ({
    sourceModel,
    parser,
    manifest,
    transpiler,
    cli,
    bootstrap,
    squirtFlush,
    squirtStream,
  }));

  return runtimeSpecPromise;
}

function canonicalLane(rawLane) {
  throw new Error("canonicalLane requires runtime spec");
}

function canonicalLaneFromSpec(rawLane, sourceModel) {
  const canonical = sourceModel.LANGUAGE_ALIASES?.[rawLane.trim().toLowerCase()];
  if (!canonical) {
    throw new ParseError(`Unsupported lane '${rawLane}'.`);
  }
  return canonical;
}

export async function parseProgramWithSpec(source, treeRoot = repoRoot()) {
  const spec = await loadRuntimeSpec(treeRoot);
  return parseProgram(source, spec.sourceModel);
}

export function parseProgram(source, sourceModel = { LANGUAGE_ALIASES: {
  js: "javascript", javascript: "javascript", node: "javascript", go: "go", golang: "go", rust: "rust", rs: "rust", zig: "zig",
} }) {
  const lines = source.split(/\r?\n/);
  const segments = [];
  let index = 0;
  let nextId = 1;

  while (index < lines.length) {
    const rawLine = lines[index];
    const stripped = rawLine.trim();

    if (!stripped || stripped.startsWith("#")) {
      index += 1;
      continue;
    }

    const fenceMatch = stripped.match(/^```([A-Za-z0-9_+-]+)(?:\s+(.*))?$/);
    if (fenceMatch) {
      const lane = canonicalLaneFromSpec(fenceMatch[1], sourceModel);
      const label = fenceMatch[2] ? fenceMatch[2].trim() : null;
      const blockStart = index + 1;
      index += 1;
      const blockLines = [];
      while (index < lines.length && lines[index].trim() !== "```") {
        blockLines.push(lines[index]);
        index += 1;
      }
      if (index >= lines.length) {
        throw new ParseError(`Unterminated fenced block starting on line ${blockStart}.`);
      }
      segments.push({
        id: nextId,
        language: lane,
        kind: "block",
        label,
        lineStart: blockStart,
        source: blockLines.join("\n").replace(/\s+$/, ""),
      });
      nextId += 1;
      index += 1;
      continue;
    }

    const colonIndex = rawLine.indexOf(":");
    if (colonIndex !== -1) {
      const lane = canonicalLaneFromSpec(rawLine.slice(0, colonIndex), sourceModel);
      const sourceText = rawLine.slice(colonIndex + 1).trimStart();
      segments.push({
        id: nextId,
        language: lane,
        kind: "line",
        label: null,
        lineStart: index + 1,
        source: sourceText,
      });
      nextId += 1;
      index += 1;
      continue;
    }

    throw new ParseError(`Could not parse line ${index + 1}: '${rawLine}'.`);
  }

  return { segments };
}

function renderLane(language, segments, spec) {
  const comment = spec.transpiler.commentPrefix[language];
  const lines = [
    `${comment} Generated by the jizzrug bootstrap runtime`,
    `${comment} Lane: ${language}`,
    "",
  ];

  for (const segment of segments) {
    lines.push(`${comment} segment ${segment.id} (${segment.kind}) from source line ${segment.lineStart}`);
    if (segment.label) {
      lines.push(`${comment} label: ${segment.label}`);
    }
    if (segment.source) {
      lines.push(segment.source);
    }
    lines.push("");
  }

  return `${lines.join("\n").replace(/\s+$/, "")}\n`;
}

export async function compileSource(sourcePath, outDir, treeRoot = repoRoot()) {
  const spec = await loadRuntimeSpec(treeRoot);
  const source = await fs.readFile(sourcePath, "utf8");
  const program = parseProgram(source, spec.sourceModel);
  await fs.mkdir(outDir, { recursive: true });

  const grouped = new Map();
  const manifest = {
    language: "jizzrug",
    version: spec.manifest.MANIFEST_VERSION,
    source: path.basename(sourcePath),
    outputs: [],
    segments: [],
  };

  for (const segment of program.segments) {
    const laneSegments = grouped.get(segment.language) ?? [];
    laneSegments.push(segment);
    grouped.set(segment.language, laneSegments);
    manifest.segments.push({
      id: segment.id,
      language: segment.language,
      kind: segment.kind,
      label: segment.label,
      lineStart: segment.lineStart,
    });
  }

  for (const language of [...grouped.keys()].sort()) {
    const outputName = `main.${spec.transpiler.extensionMap[language]}`;
    const outputPath = path.join(outDir, outputName);
    await fs.writeFile(outputPath, renderLane(language, grouped.get(language), spec), "utf8");
    manifest.outputs.push({ language, path: outputName });
  }

  await fs.writeFile(
    path.join(outDir, spec.manifest.MANIFEST_FILE_NAME ?? spec.squirtFlush.DEFAULT_PLAN_NAME),
    `${JSON.stringify(manifest, null, 2)}\n`,
    "utf8",
  );
  return manifest;
}

async function listSourceFiles(rootDir, acceptedExtensions) {
  const entries = await fs.readdir(rootDir, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const entryPath = path.join(rootDir, entry.name);
    if (entry.isDirectory()) {
      files.push(...(await listSourceFiles(entryPath, acceptedExtensions)));
      continue;
    }
    if (acceptedExtensions.some((ext) => entry.name.endsWith(ext))) {
      files.push(entryPath);
    }
  }

  return files;
}

export async function bootstrapTree(outDir, treeRoot = repoRoot()) {
  const spec = await loadRuntimeSpec(treeRoot);
  const sourceRoots = spec.bootstrap.SOURCE_ROOTS;
  const units = [];

  await fs.mkdir(outDir, { recursive: true });

  for (const sourceRoot of sourceRoots) {
    const absoluteRoot = path.join(treeRoot, sourceRoot);
    const files = await listSourceFiles(absoluteRoot, spec.sourceModel.ACCEPTED_EXTENSIONS);
    files.sort();
    for (const file of files) {
      const relativeSource = path.relative(treeRoot, file);
      const unitDir = path.join(
        outDir,
        relativeSource.replace(/\.(jizz|jizzrug|jr)$/, "").replaceAll(path.sep, "__"),
      );
      const manifest = await compileSource(file, unitDir, treeRoot);
      units.push({
        source: relativeSource,
        outDir: path.relative(outDir, unitDir) || ".",
        outputs: manifest.outputs,
      });
    }
  }

  const bootstrapManifest = {
    language: "jizzrug",
    mode: "bootstrap",
    units,
  };
  await fs.writeFile(
    path.join(outDir, "bootstrap-plan.json"),
    `${JSON.stringify(bootstrapManifest, null, 2)}\n`,
    "utf8",
  );
  return bootstrapManifest;
}

async function printHelp(treeRoot = repoRoot()) {
  const spec = await loadRuntimeSpec(treeRoot);
  console.log(spec.cli.helpText());
}

function parseFlags(args) {
  let outDir = null;
  let json = false;
  const positional = [];

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--json") {
      json = true;
      continue;
    }
    if (arg === "--out") {
      outDir = args[index + 1];
      index += 1;
      continue;
    }
    positional.push(arg);
  }

  return { outDir, json, positional };
}

async function runCum(args) {
  const spec = await loadRuntimeSpec();
  const { outDir, json, positional } = parseFlags(args);
  const source = positional[0];
  if (!source) {
    throw new Error("cum requires a source path.");
  }
  if (!spec.sourceModel.ACCEPTED_EXTENSIONS.some((ext) => source.endsWith(ext))) {
    throw new Error("source must end in .jizz, .jizzrug, or .jr");
  }
  const manifest = await compileSource(source, outDir ?? spec.cli.COMMANDS.cum.defaultOutDir);
  if (json) {
    console.log(JSON.stringify(manifest, null, 2));
  } else {
    const outputs = manifest.outputs.map((item) => item.path).join(", ");
    console.log(`Compiled ${source} into ${outDir ?? spec.cli.COMMANDS.cum.defaultOutDir}: ${outputs}`);
  }
}

async function runBootstrap(args) {
  const spec = await loadRuntimeSpec();
  const { outDir, json } = parseFlags(args);
  const manifest = await bootstrapTree(outDir ?? spec.bootstrap.DEFAULT_BOOTSTRAP_OUT_DIR);
  if (json) {
    console.log(JSON.stringify(manifest, null, 2));
  } else {
    console.log(`Bootstrapped ${manifest.units.length} jizzrug source units into ${outDir ?? spec.bootstrap.DEFAULT_BOOTSTRAP_OUT_DIR}`);
  }
}

export async function main(argv) {
  const [command, ...args] = argv;

  if (!command || command === "help" || command === "--help" || command === "-h") {
    await printHelp();
    return 0;
  }

  if (command === "cum") {
    await runCum(args);
    return 0;
  }

  if (command === "bootstrap") {
    await runBootstrap(args);
    return 0;
  }

  throw new Error(`Unknown command: ${command}`);
}
